Homework05
svtgo/cs102 pull request #10
Opened 2021-01-01 19:43 UTC by svtgo

2021-01-02 19:35 UTC, anastasiiaCher requested changes
У вас не все хорошо с юниттестами
![image](https://user-images.githubusercontent.com/28839610/103465217-981eb500-4d4a-11eb-81f6-b768cb07d23a.png)
Запустите локально, там есть ошибочки, которые надо исправлять.

2021-01-04 02:05 UTC, svtgo commented
Опять проблема с юниттестами в workflow, локально все тесты проходят
<img width="569" alt="cs102_—_-bash_—_80×24" src="https://user-images.githubusercontent.com/70940564/103495062-7573c580-4e4a-11eb-94ad-38743690042b.png">

2021-01-05 18:13 UTC, anastasiiaCher requested changes
Почему-то не работает команда `python -m unittest discover` на `ubuntu`, хм.
С тестами все ок.
По работе с реальными данными надо немного отладить пару моментов.
(За два дня, что я не смотрела вашу работу, балл не потеряется)

2021-01-05 18:13 UTC, anastasiiaCher commented on homework05/research/network.py
> +    if friends is None:
Все-таки `if not friends`

2021-01-05 18:13 UTC, anastasiiaCher commented on homework05/vkapi/friends.py
> +        "user_id": user_id if user_id is not None else "",
`user_id if user_id else ""`
Не надо перегружать лишний раз. Еще много где встречается по коду. Надо поправить.

2021-01-05 18:13 UTC, anastasiiaCher commented on homework05/vkapi/friends.py
> +def get_mutual(
Над реализацией `get_mutual()` надо подумать. Должно быть следующее: если передаются параметры `source_uid`, `target_uid`, `target_uids`, то функция должна доставать список айди общих друзей сорс-юзера и таргет-юзера. Если `target_uid` не указан, то ищутся общие друзья сорс-юзера со всеми его друзьями.
Сейчас эта функция у вас работает одинаково в обоих случаях. Плюс, если у двух юзеров нет общих друзей, кроме друг друга, то список общих друзей будет пустым.

2021-01-06 18:01 UTC, anastasiiaCher approved these changes
Сдано.

2021-01-12 21:22 UTC, closed without merging