Homework06
svtgo/cs102 pull request #12
Opened 2021-04-02 18:13 UTC by svtgo

2021-04-05 13:37 UTC, anastasiiaCher requested changes
По реализации все ок.
Добавьте файл с небольшим скриптом, демонстрирующим работу вашей реализации классификатора на собранных вами данных.

2021-04-20 10:12 UTC, anastasiiaCher requested changes
Вопрос всего один (в комментариях его расширенная версия): вы запускали скрипт, воспроизводящий вашу реализацию Байеса?

2021-04-20 10:12 UTC, anastasiiaCher commented on homework06/hw06/classifying.py
> +model = NaiveBayesClassifier(alpha=0.05)
Разве у вас есть параметр `alpha` в классе `NaiveBayesClassifier`? Рекомендую запустить скрипт и обратить внимание на ошибки, которые возникнут при его выполнении.

2021-04-20 10:12 UTC, anastasiiaCher commented on homework06/hw06/classifying.py
> +model.fit(X, y)
Модель должна обучаться на обучающей выборке, а не на полной, иначе нет смысла в машинном обучении в данной задаче.

2021-04-21 01:15 UTC, svtgo commented
<img width="506" alt="classifying_py_—_homework06-2" src="https://user-images.githubusercontent.com/70940564/115482825-39793a80-a258-11eb-81fc-f9df7c5e7217.png">
<img width="476" alt="classifying_py_—_homework06" src="https://user-images.githubusercontent.com/70940564/115482827-3aaa6780-a258-11eb-8b0a-d0c32187c8fd.png">

2021-05-07 05:16 UTC, anastasiiaCher approved these changes
Принято.

2021-05-15 07:31 UTC, closed without merging