Homework02
svtgo/cs102 pull request #2
Opened 2020-10-28 14:18 UTC by svtgo

2020-10-29 18:49 UTC, anastasiiaCher commented
1. В функции `group()` используйте списковое включение, отправив его сразу в `return`. Аналогично в `get_block()`.
2. В `find_empty_positions()` лучше возвращать не `(-1, -1)` в конце, а `None`. Тогда в `solve()` можно будет сделать проверку через `if not pos`.
3. В `find_possible_values()` можно (и нужно) не создавать кучу переменных. И можно сразу отправить выражение, соответствующее переменной `new`,в оператор `return`.

Верните заголовки функций и доктесты, как было в шаблонах. Это повлияет на некоторые операторы `return`. В целом решение хорошее, его нужно только немного улучшить.

2020-10-30 15:10 UTC, anastasiiaCher commented
Осталось только сделать списковое включение в `get_block()`.

2020-10-30 21:24 UTC, Dementiy requested changes
1. В целом все ок.
2. Надо настроить github actions, иначе работа не будет приянта
3. Репозиторий должен быть приватным

2020-10-31 17:43 UTC, anastasiiaCher commented
Все еще нет github actions и репозиторий все еще public.

2020-10-31 20:48 UTC, anastasiiaCher commented
Чтобы устранить ошибку в mypy попробуйте воспользоваться синтаксисом `# type: ignore`

2020-11-03 17:56 UTC, anastasiiaCher requested changes
Почти все ок, пара правочек.

2020-11-03 17:56 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    return []
Здесь лучше возвращать `None`, если решения нет

2020-11-03 17:56 UTC, anastasiiaCher commented on homework02/sudoku.py
> +                return (row, col)
у `return` не нужны скобки

2020-11-04 16:54 UTC, anastasiiaCher approved these changes
Все ок.

2020-11-13 00:51 UTC, closed without merging